---
title: "An Analysis of Crime in Cherry Hill"
author: "Jason Hammett"
date: "February 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Install function courtesy of CSCI 349
my.install <- function(pkg){
  if (!(pkg %in% installed.packages()[,1])){
    install.packages(pkg)
  }
  return (require(pkg, character.only=TRUE))
}
#Knitr
my.install("knitr")
#Decision Tree Libs
my.install("rpart")
my.install("rpart.plot")
#Plotting Libs
my.install("ggplot2")
my.install("ggmap")
my.install("leaflet")

#colorblind settings
# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# To use for fills, add
#scale_fill_manual(values=cbPalette)

# To use for line and point colors, add
#scale_colour_manual(values=cbPalette)
```

## R Markdown



 I'll grab the cherryHill neighborhood from the data set
```{r cherryHill}
cherryHill <- victims[which(victims$Neighborhood == "Cherry Hill"),]
```

I'm going to utilize ggmap to visualize these crimes.
```{r mapping cherry hill}
#Grab a map centered on the cherry hill neighborhood
cherryHillMap <- get_map("cherry hill, baltimore, maryland", zoom = 15)
#Plot all crimes
mapPoints <- ggmap(cherryHillMap) + geom_point(aes(x = Longitude, y = Latitude), data = cherryHill, alpha = .25)
#Titles
mapPoints <- mapPoints + ggtitle("Crime in Cherry Hill") + ylab("Latitude") + xlab("Longitude")

#Display it
mapPoints

mapPoints2 <- ggmap(cherryHillMap) + geom_point(aes(x = Longitude, y = Latitude, colour = Weapon), data = cherryHill, alpha = .75) + scale_colour_manual(values=cbbPalette)
mapPoints2 <- mapPoints2 + ggtitle("Crime in Cherry Hill by Weapon Used") + ylab("Latitude") + xlab("Longitude")

mapPoints2
```

Basic rpart decision tree on the cherryhill neighborhood.

```{r training tree on cherry hill}
#Form a 90-10 train test split
split <- sample(nrow(cherryHill), nrow(cherryHill) * 0.9)
#Divide the set into train and test
cherryHillTrain <- cherryHill[split,]
cherryHillTest <- cherryHill[-split,]
#Build the model
cherryHillModel <- rpart(cherryHillTrain, formula = CrimeCode ~ Description)
#Plot it
prp(cherryHillModel)
#Make two more models
cherryHillModel2 <- rpart(cherryHillTrain, formula = Weapon ~ Description)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
